# Generated by Django 5.1.2 on 2024-10-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_band_hometown'),
        ('listings', '0008_band_record_company'),
    ]

    operations = [
    ]
